// <auto-generated />
using System;
using INTEX_W2026_Group_2_7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INTEX_W2026_Group_2_7.Migrations.Operational
{
    [DbContext(typeof(OperationalDbContext))]
    [Migration("20260408195414_MapResidentNameColumns")]
    partial class MapResidentNameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ChannelSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("CreatedByPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("date");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImpactUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.HasIndex("CreatedByPartnerId");

                    b.HasIndex("DonationDate");

                    b.HasIndex("ReferralPostId");

                    b.HasIndex("SupporterId");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("DonationAllocations", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.DonorChurnPrediction", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RiskBand")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RunId", "DonorId");

                    b.HasIndex("DonorId");

                    b.HasIndex("ScoredAt");

                    b.ToTable("DonorChurnPredictions", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationRecordId"));

                    b.Property<decimal>("AttendanceRate")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EnrollmentStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ResidentId", "RecordDate")
                        .IsUnique();

                    b.ToTable("EducationRecords", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<decimal>("Bmi")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<decimal>("EnergyLevelScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GeneralHealthScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NutritionScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<decimal>("SleepQualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ResidentId", "RecordDate")
                        .IsUnique();

                    b.ToTable("HealthWellbeingRecords", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FamilyMembersPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationVisited")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("bit");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ResidentId", "VisitDate");

                    b.ToTable("HomeVisitations", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedUnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IntendedUse")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedCondition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("InKindDonationItems", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("IncidentReports", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime?>("CaseConferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("ServicesProvided")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("InterventionPlans", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.MlModelRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("RunId");

                    b.HasIndex("ModelName", "StartedAt");

                    b.ToTable("MlModelRuns", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignmentEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("AssignmentStart")
                        .HasColumnType("date");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("PartnerAssignments", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("EmotionalStateEnd")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EmotionalStateObserved")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FollowUpActions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterventionsApplied")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("bit");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("bit");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SessionNarrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ResidentId", "SessionDate");

                    b.ToTable("ProcessRecordings", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MetricPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("PublicImpactSnapshots", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssignedSocialWorker")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BirthStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRiskLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("DateCaseStudyPrepared")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateColbObtained")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateColbRegistered")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateEnrolled")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOfAdmission")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("bit");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("bit");

                    b.Property<bool>("FamilyIs4Ps")
                        .HasColumnType("bit");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("bit");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResidentFirstName");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("InitialCaseAssessment")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InitialRiskLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResidentLastName");

                    b.Property<string>("LengthOfStay")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PresentAge")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PwdType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReferralSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReintegrationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReintegrationType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("bit");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("bit");

                    b.HasKey("ResidentId");

                    b.HasIndex("CaseControlNo")
                        .IsUnique();

                    b.HasIndex("InternalCode")
                        .IsUnique();

                    b.HasIndex("SafehouseId");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.ResidentRiskPrediction", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<bool>("FlagForReview")
                        .HasColumnType("bit");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PredictedRisk")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("PredictedRiskNum")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RunId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ScoredAt");

                    b.ToTable("ResidentRiskPredictions", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafehouseId"));

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("int");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("SafehouseId");

                    b.HasIndex("SafehouseCode")
                        .IsUnique();

                    b.ToTable("Safehouses", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<int>("ActiveResidents")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HomeVisitationCount")
                        .HasColumnType("int");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("MonthEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("MonthStart")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessRecordingCount")
                        .HasColumnType("int");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.HasIndex("SafehouseId", "MonthStart")
                        .IsUnique();

                    b.ToTable("SafehouseMonthlyMetrics", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CallToActionType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CampaignName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaptionLength")
                        .HasColumnType("int");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("int");

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("ContentTopic")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("int");

                    b.Property<decimal>("EngagementRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("EstimatedDonationValuePhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("bit");

                    b.Property<int>("FollowerCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("Forwards")
                        .HasColumnType("int");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("bit");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impressions")
                        .HasColumnType("int");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("MentionsCount")
                        .HasColumnType("int");

                    b.Property<int>("NumHashtags")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformPostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PostHour")
                        .HasColumnType("int");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("int");

                    b.Property<int>("Reach")
                        .HasColumnType("int");

                    b.Property<int>("Saves")
                        .HasColumnType("int");

                    b.Property<string>("SentimentTone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlatformPostId")
                        .IsUnique();

                    b.ToTable("SocialMediaPosts", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FirstDonationDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("SupporterId");

                    b.HasIndex("Email");

                    b.ToTable("Supporters", (string)null);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Donation", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Partner", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("INTEX_W2026_Group_2_7.Data.SocialMediaPost", null)
                        .WithMany()
                        .HasForeignKey("ReferralPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("INTEX_W2026_Group_2_7.Data.Supporter", null)
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.DonationAllocation", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEX_W2026_Group_2_7.Data.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.DonorChurnPrediction", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Supporter", null)
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("INTEX_W2026_Group_2_7.Data.MlModelRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.EducationRecord", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.HealthWellbeingRecord", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.HomeVisitation", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.InKindDonationItem", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.IncidentReport", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEX_W2026_Group_2_7.Data.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.InterventionPlan", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.PartnerAssignment", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEX_W2026_Group_2_7.Data.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.ProcessRecording", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.Resident", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.ResidentRiskPrediction", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("INTEX_W2026_Group_2_7.Data.MlModelRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX_W2026_Group_2_7.Data.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("INTEX_W2026_Group_2_7.Data.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
